### ISSUE TITLE
How should links to other articles be created?

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/docs#119]
Two questions: 

* Relative paths? I'm assuming yes.

* Should there be a file type added? For example, when referencing `../modeling/whatever.md` should we say `../modeling/whatever`, `../modeling/whatever.html`, etc.

**Comment by marbemac** [comment]
Good question.

- Relative paths? Yup!
- Should there be a file type added? Yeah the relative path should be valid, as if it were code. So, include the file extension. If it is working correctly, github should pick it up as well and the articles should be linked when viewing here.

**Comment by rossmcdonald** [comment]
Sounds good! Thanks!
