### ISSUE TITLE
Maybe store images elsewhere?

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/docs#127]
The repo as of this morning is now ~1.1GB in size, and we're not even halfway to being finished. Should we consider putting images in a separate location? It's not a huge deal, but it will make pushing and pulling take considerably longer.

**Comment by marbemac** [comment]
I think the real issue here is why is the repo 1.1gb in size - no matter what we won't want to be serving up such large assets to visitors. What can we do to compress or otherwise make the gifs smaller?

**Comment by pytlesk4** [comment]
Maybe docs are the issue in general, if we don't write them, then this repo will be fast to check out.

**Comment by rossmcdonald** [comment]
I think it's partly due to multiple versions of GIFs and images being retained in the git history, even though those images are not actually used by anything anymore. Unfortunately there's not a good way to remove them without overwriting the repository history. Using the "squash" merge method should hopefully get rid of most of these before they reach develop, but the ones that are already there will be tough to fix.

I found a nifty little script that displays the size of different blobs for reference:
```
$ ./size.sh
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size   pack   SHA                                       location
32106  31957  cfd1155b2d84b262a248a76753d5d0358f71b854  assets/gifs/validation-todos-prism-local.gif
32106  31957  cfd1155b2d84b262a248a76753d5d0358f71b854  assets/gifs/validation-todos-prism-local.gif
29940  29777  b72f0da883e74b4b7ef713828f98e83da0638892  assets/gifs/prism-install.gif
29940  29777  b72f0da883e74b4b7ef713828f98e83da0638892  assets/gifs/prism-install.gif
25569  25435  c96907318204e0a3dbd2fa35a00f2e215e54f71c  assets/gifs/mock-hello-prism-local.gif
25569  25435  c96907318204e0a3dbd2fa35a00f2e215e54f71c  assets/gifs/mock-hello-prism-local.gif
25393  25277  63cbf7571b42fb2e01462657ea43e4ade81cfd6e  assets/gifs/ref-other-sources-hubs.gif
25155  25053  044b09871378c20d3e0fa41401314ec5f273041c  assets/gifs/routing-hubs.gif
23267  23198  45ddb82fc4384e8d6108f0cefe5def94d53a7a9b  assets/gifs/validation-todos-prism-rule.gif
23267  23198  45ddb82fc4384e8d6108f0cefe5def94d53a7a9b  assets/gifs/validation-todos-prism-rule.gif
```

The size of the GIF's in general is also problematic. Right now the `gifs` folder (excluding git history) is ~309MB. Some of the individual GIF's are >20MB in size, so those will definitely need to be slimmed down. I've been trying to keep mine down < 5MB, but it's tough for longer GIFs. 

Maybe we could try setting some ground rules on images/gifs? Like no GIF's > 5MB? There might be a way to optimize the ones that are already created to trim them down, but I'm not familiar with any software that does that.

**Comment by marbemac** [comment]
Agreed on the guidelines. Additionally, I tried https://ezgif.com/optimize with the lossy option set to 100, which reduced a 23mb gif to 3.9mb without significant visual difference.

60 compression level seems to be a good sweet spot.

For standards, I would suggest:

Record:
- max 1000px width/height on initial capture size
- max 15 seconds long

Save:
- original size
- low framerate

Compress: https://ezgif.com/optimize with 60 as the compression level. This should keep all of our gifs well under 3mb. Here is an example:

![ezgif com-optimize 1](https://user-images.githubusercontent.com/847542/35751881-9e2de6c8-081f-11e8-95e2-84142a423d81.gif)
