### ISSUE TITLE
articles/modeling/object-inheritance.md

### ISSUE THREAD

**Issue by rowa97** [stoplightio/docs#137]

**Comment by rossmcdonald** [comment]
I'm going to go ahead and rewrite this one, but my initial notes are below for reference.

---

> A model contains common resuable information that can be referenced in your endpoint definitions or other models in your API design.

Typo: resuable -> reusable

The phrasing is a little confusing, maybe update it to the following:

> A model contains properties that can be reused and referenced by endpoint definitions, shared objects, and other models.

---

> When a model derives its properties from another model, the event is called inheritance.

The use of 'the event' is a little strange in this context. Maybe update to:

> Inheritance is when a model derives its properties from another model.

---

> The model which contains the common set of properties and fields becomes a parent to other models, and it is called the base type.

Maybe update to:

> When a model inherits from another model, the model being inherited from is known as a base type (or parent).

---

> The model which inherits the common set of properties and fields is known as the derived type.

I'm not sure if this deserves it's own bullet. Maybe roll it into the bullet above as a second sentence?

> Similarly, a model that is inheriting properties from a base type is known as a derived type (or child).

---

> If a base type inherits its properties from another model, the derived type automatically inherits the same properties indicating that inheritance is transitive.

Maybe update to:

> When a base type inherits properties from another model, any derived types will also automatically inherit the properties as well. For example, if model C is a derived type of model B, and model B is a derived type of model A, then model C is also a derived type of model A. In mathematics, this is known as the [transitive property](https://en.wikipedia.org/wiki/Transitive_relation).

---

> OpenAPI Specification v2 uses the allOf syntax to declare inheritance.

Maybe update to:

> To specify that a model should inherit from a base type, use the `allOf` option (under "Combination Types") when building the model. By specifying `allOf` and referencing the base type, the model will automatically inherit all of the parent model's objects. A model can also inherit from multiple base types as needed.

---

The example is also not great, and is copied from the polymorphism doc.
