### ISSUE TITLE
articles/editor/editor-configuration.md

### ISSUE THREAD

**Issue by rowa97** [stoplightio/docs#29]
* Link to other environments
* Default config

**Comment by rossmcdonald** [comment]
Can I get more information on what this article is supposed to be about? Is this for configuring the editor environment variables, or something else?

**Comment by marbemac** [comment]
Totally, we'll briefly go over each article in our meeting today, and I plan to create a quick outline for all the articles this weekend.

**Comment by marbemac** [comment]
This one is about the .stoplight.yml config file and its options (will be a very short article for now).
