### ISSUE TITLE
articles/testing/using-variables.md

### ISSUE THREAD

**Issue by rowa97** [stoplightio/docs#52]
* [x] overview
* [x] environment
* [x] context

**Comment by rossmcdonald** [comment]
@rowa97 @marbemac On the spreadsheet there are three articles for variables:

```
Using Variables (Overview) *
Using Variables (environments) *
Using Variables (Context)  *
```

Should these be in the same article? Or should I create new issues for them?

**Comment by rowa97** [comment]
@rossmcdonald I noticed that a couple days ago and created files for them, I guess I forgot to update the issue. Yes, they are 3 separate articles.

**Comment by rossmcdonald** [comment]
@rowa97 Cool, just wanted to double check. I'll create issues for the other two.
